# Generated by Django 5.1.4 on 2025-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('sex', models.IntegerField(blank=True, choices=[('0', '남자'), ('1', '여자')], null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
