# Generated by Django 5.1.4 on 2025-01-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_is_deleted_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '남자'), (1, '여자')], null=True),
        ),
    ]
