version: '3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bookshorts
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/Backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bookshorts

  prometheus-monitoring:
    image: prom/prometheus:v2.45.6
    container_name: prometheus-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - bookshorts

  grafana-monitoring:
    image: grafana/grafana:9.5.20 
    container_name: grafana-monitoring 
    volumes:
      - ./grafana:/etc/grafana/provisioning 
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - bookshorts

  cadvisor-monitoring:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor-monitoring
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - bookshorts

  node-exporter-monitoring:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter-monitoring
    ports:
      - "9100:9100"
    networks:
      - bookshorts

networks:
  bookshorts:
    driver: bridge