version: '3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bookshorts
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./
    command: >
      sh -c " 
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/Backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bookshorts

networks:
  bookshorts:
    driver: bridge