# Generated by Django 5.1.4 on 2025-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, max_length=1000, unique=True),
        ),
    ]
