# Generated by Django 5.1.4 on 2025-01-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
        ('todays_shorts', '0001_initial'),
        ('users', '0003_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaysshorts',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorts.short'),
        ),
        migrations.AlterField(
            model_name='todaysshorts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
